import { useEffect } from "react";
import Head from "next/head";
import Video from "../components/Video";
import { getVideosRequest } from "../api";
import Banner from "../components/Ads/Banner";
import Floating from "../components/Ads/Floating";

export default function Home({ videos, nextPageToken }) {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Film Farm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-wrap justify-center">
        <Floating />
        <main className="grid grid-cols-12 gap-3 px-3 bg-bunker-500 max-w-[980px]">
          <div className="col-span-12">
            <Banner />
            <Banner />
            <Banner />
          </div>
          {videos.map((video) => (
            <div
              className="col-span-6 sm:col-span-4 lg:col-span-3"
              key={video.id}
            >
              <Video video={video} />
            </div>
          ))}
        </main>
        <Floating />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const data = await getVideosRequest();

  return {
    props: {
      videos: data.items,
      nextPageToken: data.nextPageToken,
    },
  };
}
