import { useEffect } from "react";
import Head from "next/head";
import Video from "../components/Video";
import videoAPI, { getVideosRequest } from "../api";

export default function Home({ videos, nextPageToken}) {
  return (
    <main className="min-h-screen bg-bunker-500">
      <Head>
        <title>Film Farm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-12 gap-3 p-3">
        {videos.map((video) => (
          <div className="col-span-6 sm:col-span-4 lg:col-span-3" key={video.id}>
            <Video video={video} />
          </div>
        ))}
      </div>
    </main>
  );
}

export async function getServerSideProps(context) {
  const data = await getVideosRequest();

  return {
    props: {
      videos: data.items,
      nextPageToken: data.nextPageToken,
    },
  };
}
