import { useEffect } from "react";
import Head from "next/head";
import Video from "../components/Video";
import { getVideosRequest } from "../api";
import Banner from "../components/Ads/Banner";
import Floating from "../components/Ads/Floating";

export default function Home({ videos, nextPageToken }) {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Film Farm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-wrap justify-center">
        <Floating />
        <div className="max-w-screen-lg ">
          <Banner width="980px" height="90px" />
          <Banner width="980px" height="90px" />
          <Banner width="980px" height="90px" />
          <main className="grid max-w-screen-lg grid-cols-12 gap-3 p-3 bg-bunker-500">
            {videos.map((video) => (
              <div
                className="col-span-6 sm:col-span-4 lg:col-span-3"
                key={video.id}
              >
                <Video video={video} />
              </div>
            ))}
          </main>
        </div>
        <Floating />
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const data = await getVideosRequest();

  return {
    props: {
      videos: data.items,
      nextPageToken: data.nextPageToken,
    },
  };
}
